<?php

namespace Repository;

/**
 * DomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomRepository extends \Doctrine\ORM\EntityRepository
{
    public function pobierzWszystko()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m')->from('Entity\Dom', 'm')->join('m.nieruchomosc', 'n');
        return $qb->getQuery()->getResult();
    }

    public function pobierzPoNieruchomosci($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m')->from('Entity\Dom', 'm')->join('m.nieruchomosc', 'n')->where('n.id = :id')->setParameter("id", $id);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
