<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MieszkanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MieszkanieRepository extends EntityRepository
{
    public function pobierzWszystko()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m','n', 'mi')
            ->from('Entity\Mieszkanie', 'm')
            ->join('m.nieruchomosc', 'n')
            ->join('n.miasto', 'mi');

        return $qb->getQuery()->getResult();
    }

    public function pobierzPoNieruchomosci($id)
    {
        
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m','n', 'mi')
            ->from('Entity\Mieszkanie', 'm')
            ->join('m.nieruchomosc', 'n')
            ->join('n.miasto', 'mi')
            ->where('n.id = :id')->setParameter("id", $id);
 
        return $qb->getQuery()->getOneOrNullResult();
    }
}
